// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUp4d4k6Gbn8F9lrs7ZZM-wijAQG-TvHc',
    appId: '1:471701999689:android:c840aa6e79b16a9fc26f98',
    messagingSenderId: '471701999689',
    projectId: 'telekommanagement-6cb8e',
    databaseURL: 'https://telekommanagement-6cb8e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'telekommanagement-6cb8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArsbu2voB4_CpVDfk__apxpmwzUSSOzOg',
    appId: '1:471701999689:ios:7aeb7876dbd64b0dc26f98',
    messagingSenderId: '471701999689',
    projectId: 'telekommanagement-6cb8e',
    databaseURL: 'https://telekommanagement-6cb8e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'telekommanagement-6cb8e.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerProject',
  );
}
